export const siteConfig = {
  name: "Zerror Studios | Animated Websites, eCommerce & Custom CMS",
  description: "Zerror Studios crafts next-gen GSAP-powered websites, custom eCommerce solutions, and advanced CMS for brands that dare to stand out. Elevate your digital presence today.",
  url: "https://www.zerrorstudios.com/",
  locale: "en_IN",
  language: "en-IN",
  ogImage: "/og.png",
  keywords: [
    "Web Development Company in Mumbai",
    "E-commerce Website Development",
    "Custom Web Development Services",
    "Shopify Development Agency",
    "App Development Company India",
    "UI/UX Design Agency",
    "SEO Services",
    "Creative Digital Agency Mumbai",
    "GSAP Animation Websites",
    "Best Web Design Company",
    "Headless E-commerce Solutions",
    "Progressive Web Apps (PWA)",
    "Mobile-First Web Design",
    "Custom Software Development",
    "Wix",
    "Shopify",
    "Zerror",
    "Zerror Studios",
    "Studio",
    "GSAP",
    "Three.js",
    "3js",
    "Modern Web Dev",
    "3js Animation",
  ],
  contact: {
    phone: "+917738802437",
    email: "hello@zerrorstudios.com",
  },
  address: {
    street: "",
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "401105",
    country: "IN",
  },
  socials: {
    facebook: "",
    instagram: "https://www.instagram.com/wearezerrorians/",
    twitter: "",
    linkedin: "https://in.linkedin.com/company/zerror-studios-mumbai",
  },
};

export const siteRoutes = [
  {
    path: "/",
    label: "Home",
    title: "Home",
    description: siteConfig.description,
    priority: 1,
  },
  {
    path: "/about",
    label: "About",
    title: "About",
    description: "",
    priority: 0.8,
  },
  {
    path: "/contact",
    label: "Contact",
    title: "Contact",
    description: "",
    priority: 0.7,
  },
  {
    path: "/demo",
    label: "Demo",
    title: "Demo",
    description: "",
    priority: 0.7,
  },
  {
    path: "/expertise",
    label: "Expertise",
    title: "Expertise",
    description: "",
    priority: 0.8,
  },
  {
    path: "/pitchdeck",
    label: "Pitchdeck",
    title: "Pitchdeck",
    description: "",
    priority: 0.7,
  },
  {
    path: "/work",
    label: "Work",
    title: "Work",
    description: "",
    priority: 0.8,
  },
];
